[CES-199] - Avoid modules dependencies from existing resources
pagopa/dx pull request #144
Opened 2024-10-22 13:55 UTC by christian-calabrese

### List of changes

### Motivation and context

### Type of changes

- [ ] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Other information

2024-10-22 14:57 UTC, gunzip requested changes

2024-10-22 14:57 UTC, gunzip commented on infra/modules/azure_app_service_plan_autoscaler/variables.tf
> +  - Provide either 'app_service_name' or 'function_app_name'.
What about having an app service autoscaler module AND a function autoscaler module instead? you may consider to share most of the code but this configuration.

2024-10-22 14:57 UTC, gunzip commented on infra/modules/azure_app_service_plan_autoscaler/variables.tf
> +  - Provide either 'app_service_name' or 'function_app_name'.
another option is to something like this instead:

```hcl
variable "target_service" {
  type = object({
    app_service = optional(object({
      app_service_id      = string
      app_service_name    = string
      app_service_plan_id = string
      location            = string
    }))
    function_app = optional(object({
      function_app_id   = string
      function_app_name = string
      location          = string
    }))
  })

  validation {
    condition = length([for v in [var.target_service.app_service, var.target_service.function_app] : v if v != null]) == 1
    error_message = "You must define either app_service or function_app, but not both."
  }
}
```

2024-10-22 14:57 UTC, gunzip commented on infra/modules/azure_app_service_plan_autoscaler/variables.tf
>    validation {
see comment above to simplify this logic. I think this would be a breaking change anyway.

2024-10-22 14:57 UTC, gunzip commented on infra/modules/azure_role_assignments/modules/cosmos/variables.tf
> +    account_id          = optional(string)
should be documented into var description

2024-10-22 14:57 UTC, gunzip commented on infra/modules/azure_role_assignments/modules/event_hub/variables.tf
> +  For new Event Hubs being created concurrently:
what do you mean here with "new Event Hubs being created concurrently"?

2024-10-22 14:57 UTC, gunzip commented on infra/modules/azure_role_assignments/variables.tf
> +    account_id          = optional(string)
should be documented

2025-03-07 08:35 UTC, closed without merging

2025-03-07 08:35 UTC, christian-calabrese commented
Closed cause the issue has been tackled with single PRs